listener 8884
cafile certs2/ca.pem
certfile certs2/server.pem
keyfile certs2/server-key.pem
tls_version tlsv1.2
require_certificate true
allow_anonymous true
log_type all
log_dest stdout
max_queued_messages 1000